# Generated by Django 2.0.5 on 2018-05-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=1000, null=True)),
                ('nodeData', models.CharField(max_length=1000)),
                ('lchild', models.CharField(blank=True, max_length=500, null=True)),
                ('rchild', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Tree',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='node',
            name='TreeRoot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tree'),
        ),
    ]
